# Generated by Django 4.2 on 2023-04-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("provider", models.CharField(max_length=100)),
                ("token", models.CharField(max_length=255)),
                ("scheduled_date", models.DateTimeField()),
                ("is_published", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="image",
            name="post",
        ),
        migrations.RemoveField(
            model_name="post",
            name="account",
        ),
        migrations.RemoveField(
            model_name="video",
            name="post",
        ),
        migrations.DeleteModel(
            name="Hashtag",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="SocialMediaAccount",
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
