# Generated by Django 4.2 on 2023-04-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediaaccount",
            name="platform",
            field=models.CharField(
                choices=[
                    ("FB", "Facebook"),
                    ("TW", "Twitter"),
                    ("IG", "Instagram"),
                    ("LI", "LinkedIn"),
                    ("GH", "Github"),
                ],
                max_length=2,
            ),
        ),
    ]
