# Generated by Django 4.2 on 2023-04-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="uuid",
            field=models.CharField(
                default="ffed9462-a4c2-4971-b65f-7154b6eabb8a",
                max_length=255,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
