# Generated by Django 4.2 on 2023-04-20 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_postmodel_remove_image_post_remove_post_account_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("token", models.CharField(max_length=255)),
                ("provider", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="postmodel",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="postmodel",
            name="token",
        ),
        migrations.RemoveField(
            model_name="postmodel",
            name="username",
        ),
        migrations.AddField(
            model_name="postmodel",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.usermodel",
            ),
        ),
    ]
