# Generated by Django 4.2 on 2023-04-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_remove_usermodel_provider_remove_usermodel_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmodel",
            name="token",
            field=models.CharField(max_length=255),
        ),
    ]
