# Generated by Django 4.2 on 2023-04-20 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_alter_socialmediaaccount_platform"),
        ("backend", "0003_usermodel_remove_postmodel_provider_and_more"),
    ]

    operations = []
